FROM cloudbees/jnlp-slave-with-java-build-tools


USER root

RUN \
	cd /usr/local && \
	curl -L https://services.gradle.org/distributions/gradle-3.4.1-bin.zip -o gradle-3.4.1-bin.zip && \
	unzip gradle-3.4.1-bin.zip && \
	rm gradle-3.4.1-bin.zip

ENV GRADLE_HOME=/usr/local/gradle-3.4.1
ENV PATH=$GRADLE_HOME/bin:$PATH

USER jenkins


ENTRYPOINT ["jenkins-slave"]
