FROM microsoft/azure-cli


RUN \
	curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
	chmod +x ./kubectl && \
	mv ./kubectl /usr/local/bin/kubectl


RUN \ 
	mkdir /usr/local/terraform && \
	cd /usr/local/terraform && \
	curl -L https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip -o terraform_0.11.7_linux_amd64.zip && \
	unzip terraform_0.11.7_linux_amd64.zip && \
	rm terraform_0.11.7_linux_amd64.zip 

ENV PATH=/usr/local/terraform:$PATH

RUN \
	cd /usr/local && \
	curl -L https://github.com/Azure/acs-engine/releases/download/v0.20.2/acs-engine-v0.20.2-linux-amd64.zip -o acs-engine-v0.20.2-linux-amd64.zip && \
	unzip acs-engine-v0.20.2-linux-amd64.zip && \
	rm acs-engine-v0.20.2-linux-amd64.zip

ENV PATH=/usr/local/acs-engine-v0.20.2-linux-amd64:$PATH